# Site settings
title: Benjamin Parry
email: benjamin@parry.is


github-project-url: https://github.com/benjaminparry/

description: Benjamin Parry ~ Design Researcher ~ Personal Writings.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://benjamin.parry.is" # the base hostname & protocol for your site

# Build from/to
# source:      _source
# destination: _deploy

exclude: [node_modules, gulpfile.js, source]

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:title/

# Collections
collections:
  collecting:
    output: true
    permalink: /:collection/:path/
  making:
    output: true
    permalink: /:collection/:path/
  my_tags:
    output: true
    permalink: /tagging/:name/

defaults:
  - scope:
      path: ""
      type: collecting
    values:
      layout: collecting
  - scope:
      path: ""
      type: my_tags
    values:
      layout: tagging

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
