# Site settings
title: Benjamin Parry
email: benjamin@parry.is


github-project-url: https://github.com/benjaminparry/

description: Benjamin Parry ~ Design Researcher ~ Personal Writings.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://benjamin.parry.is" # the base hostname & protocol for your site

# Build from/to
# source:      _source
# destination: _deploy

exclude: [node_modules, gulpfile.js, source]

# Build settings
markdown: kramdown

# Collections
collections:
  collecting:
    output: true
    permalink: /:collection/:path/
  making:
    output: true
    permalink: /:collection/:path/
  my_tags:
    output: true
    permalink: /tagging/:name/

defaults:
  - scope:
      path: ""
      type: collecting
    values:
      layout: collecting
  - scope:
      path: "_posts/writing"
      type: posts
    values:
      category: writing
      permalink: /:categories/:year/:month/:title/
      filed-under: /writing/
      layout: post
  - scope:
      path: "_posts/links"
      type: posts
    values:
      category: links
      permalink: /collecting/:categories/:year/:month/:title/
      filed-under: /collecting/links/
      layout: post
  - scope:
      path: "_posts/thoughts"
      type: posts
    values:
      category: thoughts
      permalink: /collecting/:categories/:year/:month/:title/
      filed-under: /collecting/thoughts/
      layout: post
  - scope:
      path: "_posts/lists"
      type: posts
    values:
      category: lists
      permalink: /collecting/:categories/:title/
      filed-under: /collecting/lists/
      layout: post
  - scope:
      path: ""
      type: my_tags
    values:
      layout: tagging

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
